# Generated by Django 6.0.4 on 2026-05-11 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campusConnectApp', '0001_initial'),
    ]

    operations = [
    ]
